export const USER_LOGIN = 'USER_LOGIN';
export const FETCH_ITEMS_FROM_SERVER = 'FETCH_ITEMS_FROM_SERVER';
export const LIKE = 'LIKE';
export const DISLIKE = 'DISLIKE';
export const RECOMMEND_FOR_USER = 'RECOMMEND_FOR_USER';